title: Geek forever
description: 0x024
author: wen zhang
logo: /static/img/avatar.png
github: https://github.com/0x024
about: 一个学焊接工程的geek爱好者

baseurl: "https://0x024.github.io"
url: "https://0x024.github.io"

disqus_shortname: simplecell
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: ["Python","ubuntu","Raspberry","Shadowsocks","Arduino",
            "Metasploit","C118"]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
